<?php
/**
 * Created by PhpStorm.
 * User: koala
 * Date: 20/01/16
 * Time: 下午 04:00
 */

namespace App\Http\Controllers;


class BaseWechatAuthController extends BaseController
{
    public function __construct(Request $request)
    {
        parent::__construct(); // TODO: Change the autogenerated stub
        $this->middleware('wechat');
    }
}