<?php

namespace App\Repositories;

use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\BabyVoteRepository;
use App\Model\BabyVote;
use App\Validators\BabyVoteValidator;
use Prettus\Repository\Traits\CacheableRepository;

/**
 * Class BabyVoteRepositoryEloquent
 * @package namespace App\Repositories;
 */
class BabyVoteRepositoryEloquent extends BaseRepository implements BabyVoteRepository
{
    use CacheableRepository;
    /**
     * Specify Model class name
     *
     * @return string
     */

    protected $cacheMinutes = 90;
    public function model()
    {
        return BabyVote::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {

        return BabyVoteValidator::class;
    }

    public function presenter()
    {
        return "App\\Presenters\\BabyVotePresenter"; // TODO: Change the autogenerated stub
    }

    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
}
