<?php

namespace App\Repositories;

use App\Presenters\BankVotePresenter;
use App\Transformers\BankVoteTransformer;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\BankVoteRepository;
use App\Model\BankVote;
use App\Validators\BankVoteValidator;
use Prettus\Repository\Traits\CacheableRepository;

/**
 * Class BankVoteRepositoryEloquent
 * @package namespace App\Repositories;
 */
class BankVoteRepositoryEloquent extends BaseRepository implements BankVoteRepository
{
    use CacheableRepository;
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return BankVote::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {

        return BankVoteValidator::class;
    }


    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }

    public function presenter()
    {
        return BankVotePresenter::class; // TODO: Change the autogenerated stub
    }
}
