<?php

namespace App\Repositories;

use App\Presenters\GuozhiyuanVotePresenter;
use Prettus\Repository\Eloquent\BaseRepository;
use Prettus\Repository\Criteria\RequestCriteria;
use App\Repositories\GuozhiyuanVoteRepository;
use App\Model\GuozhiyuanVote;
use App\Validators\GuozhiyuanVoteValidator;

/**
 * Class GuozhiyuanVoteRepositoryEloquent
 * @package namespace App\Repositories;
 */
class GuozhiyuanVoteRepositoryEloquent extends BaseRepository implements GuozhiyuanVoteRepository
{
    /**
     * Specify Model class name
     *
     * @return string
     */
    public function model()
    {
        return GuozhiyuanVote::class;
    }

    /**
    * Specify Validator class name
    *
    * @return mixed
    */
    public function validator()
    {

        return GuozhiyuanVoteValidator::class;
    }


    /**
     * Boot up the repository, pushing criteria
     */
    public function boot()
    {
        $this->pushCriteria(app(RequestCriteria::class));
    }
    public function presenter()
    {
        return GuozhiyuanVotePresenter::class; // TODO: Change the autogenerated stub
    }
}
